import { AcfunChannel } from '../types/acfun'

export const AcfunConstants = {
    all: { name: '综合榜单', channelId: '', subChannelId: '' },
    drama: { name: '番剧', channelId: 155, subChannelId: '' },
    drama_tv: { name: '番剧 · TV动画', channelId: 155, subChannelId: 67 },
    drama_theater: { name: '番剧 · 剧场动画', channelId: 155, subChannelId: 180 },
    drama_guochang: { name: '番剧 · 国产动画', channelId: 155, subChannelId: 120 },
    animation: { name: '动画', channelId: 1, subChannelId: '' },
    animation_synthesis: { name: '动画 · 动画综合', channelId: 1, subChannelId: 106 },
    animation_short: { name: '动画 · 短片·手书·配音', channelId: 1, subChannelId: 190 },
    animation_mad_amw: { name: '动画 · MAD·AMV', channelId: 1, subChannelId: 107 },
    animation_mmd: { name: '动画 · MMD·3D', channelId: 1, subChannelId: 108 },
    animation_virtual: { name: '动画 · 虚拟偶像', channelId: 1, subChannelId: 207 },
    animation_news: { name: '动画 · 动画资讯', channelId: 1, subChannelId: 159 },
    animation_cosplay_voice: { name: '动画 · COSPLAY·声优', channelId: 1, subChannelId: 133 },
    animation_tokusatsu: { name: '动画 · 特摄', channelId: 1, subChannelId: 99 },
    animation_drama: { name: '动画 · 番剧二创', channelId: 1, subChannelId: 212 },
    entertainment: { name: '娱乐', channelId: 60, subChannelId: '' },
    entertainment_funny: { name: '娱乐 · 搞笑', channelId: 60, subChannelId: 206 },
    entertainment_demon: { name: '娱乐 · 鬼畜', channelId: 60, subChannelId: 87 },
    entertainment_star: { name: '娱乐 · 明星', channelId: 60, subChannelId: 188 },
    life: { name: '生活', channelId: 201, subChannelId: '' },
    life_daily: { name: '生活 · 生活日常', channelId: 201, subChannelId: 86 },
    life_cute: { name: '生活 · 萌宠', channelId: 201, subChannelId: 88 },
    life_food: { name: '生活 · 美食', channelId: 201, subChannelId: 89 },
    life_travel: { name: '生活 · 旅行', channelId: 201, subChannelId: 204 },
    life_manual: { name: '生活 · 手工·绘画', channelId: 201, subChannelId: 127 },
    life_beauty: { name: '生活 · 美妆·造型', channelId: 201, subChannelId: 205 },
    music: { name: '音乐', channelId: 58, subChannelId: '' },
    music_cure: { name: '音乐 · 治愈系', channelId: 58, subChannelId: 215 },
    music_original: { name: '音乐 · 原创·翻唱', channelId: 58, subChannelId: 136 },
    music_play: { name: '音乐 · 演奏·乐器', channelId: 58, subChannelId: 137 },
    music_vocal_oid: { name: '音乐 · Vocaloid', channelId: 58, subChannelId: 103 },
    music_comprehensive: { name: '音乐 · 综合音乐', channelId: 58, subChannelId: 139 },
    music_radio: { name: '音乐 · 音乐选集·电台', channelId: 58, subChannelId: 185 },
    dance: { name: '舞蹈·偶像', channelId: 123, subChannelId: '' },
    dance_lamb: { name: '舞蹈·偶像 · 宅舞', channelId: 123, subChannelId: 134 },
    dance_integrated: { name: '舞蹈·偶像 · 综合舞蹈', channelId: 123, subChannelId: 135 },
    dance_idol: { name: '舞蹈·偶像 · 偶像', channelId: 123, subChannelId: 129 },
    dance_chinese_dance: { name: '舞蹈·偶像 · 中国舞', channelId: 123, subChannelId: 208 },
    game: { name: '游戏', channelId: 59, subChannelId: '' },
    game_pvp: { name: '游戏 · 王者荣耀', channelId: 59, subChannelId: 214 },
    game_mc: { name: '游戏 · 我的世界', channelId: 59, subChannelId: 210 },
    game_gp: { name: '游戏 · 和平精英', channelId: 59, subChannelId: 216 },
    game_id5: { name: '游戏 · 第五人格', channelId: 59, subChannelId: 217 },
    game_lol: { name: '游戏 · 英雄联盟', channelId: 59, subChannelId: 85 },
    game_e_sports: { name: '游戏 · 电子竞技', channelId: 59, subChannelId: 145 },
    game_online: { name: '游戏 · 网络游戏', channelId: 59, subChannelId: 186 },
    game_stand_alone: { name: '游戏 · 主机单机', channelId: 59, subChannelId: 84 },
    game_mobile: { name: '游戏 · 手机游戏', channelId: 59, subChannelId: 187 },
    game_board: { name: '游戏 · 桌游卡牌', channelId: 59, subChannelId: 165 },
    science: { name: '科技', channelId: 70, subChannelId: '' },
    science_garage: { name: '科技 · 手办模玩', channelId: 70, subChannelId: 209 },
    science_science: { name: '科技 · 科技制造', channelId: 70, subChannelId: 90 },
    science_humanities_popularization: { name: '科技 · 人文科普', channelId: 70, subChannelId: 189 },
    science_car: { name: '科技 · 汽车', channelId: 70, subChannelId: 122 },
    science_numerical: { name: '科技 · 数码家电', channelId: 70, subChannelId: 91 },
    science_speech: { name: '科技 · 演讲·公开课', channelId: 70, subChannelId: 151 },
    science_advertisement: { name: '科技 · 广告', channelId: 70, subChannelId: 149 },
    video: { name: '影视', channelId: 68, subChannelId: '' },
    video_k_pop: { name: '影视 · 影视混剪', channelId: 68, subChannelId: 219 },
    video_preview: { name: '影视 · 预告·花絮', channelId: 68, subChannelId: 192 },
    video_movie: { name: '影视 · 电影杂谈', channelId: 68, subChannelId: 193 },
    video_chasing: { name: '影视 · 追剧社', channelId: 68, subChannelId: 194 },
    video_show: { name: '影视 · 综艺show', channelId: 68, subChannelId: 195 },
    video_short: { name: '影视 · 纪录片·短片', channelId: 68, subChannelId: 196 },
    sport: { name: '体育', channelId: 69, subChannelId: '' },
    sport_comprehensive: { name: '体育 · 综合体育', channelId: 69, subChannelId: 152 },
    sport_football: { name: '体育 · 足球', channelId: 69, subChannelId: 94 },
    sport_basketball: { name: '体育 · 篮球', channelId: 69, subChannelId: 95 },
    sport_combat: { name: '体育 · 搏击健身', channelId: 69, subChannelId: 153 },
    sport_speed: { name: '体育 · 极限竞速', channelId: 69, subChannelId: 93 },
    fish: { name: '鱼塘', channelId: 125, subChannelId: '' },
    fish_law: { name: '鱼塘 · 普法安全', channelId: 125, subChannelId: 183 },
    fish_military: { name: '鱼塘 · 国防军事', channelId: 125, subChannelId: 92 },
    fish_history: { name: '鱼塘 · 历史', channelId: 125, subChannelId: 131 },
    fish_positive: { name: '鱼塘 · 新鲜事·正能量', channelId: 125, subChannelId: 132 },
    article: { name: '文章', channelId: 63, subChannelId: '' },
    article_anime: { name: '文章 · 动漫', channelId: 63, subChannelId: 184 },
    article_information: { name: '文章 · 资讯', channelId: 63, subChannelId: 110 },
    article_life: { name: '文章 · 生活', channelId: 63, subChannelId: 73 },
    article_game: { name: '文章 · 游戏', channelId: 63, subChannelId: 164 },
    article_advertisement: { name: '文章 · 广而告之', channelId: 63, subChannelId: 76 }
} as const
