export const AppleRankList = {
    free: { name: '免费 App 排行', value: 'topfreeapplications' },
    paid: { name: '付费 App 排行', value: 'toppaidapplications' },
    gross: { name: '畅销 App 排名', value: 'topgrossingapplications' },

    'free-ipad': { name: '免费 iPad App 排行', value: 'topfreeipadapplications' },
    'paid-ipad': { name: '付费 iPad App 排行', value: 'toppaidipadapplications' },
    'gross-ipad': { name: '畅销 iPad App 排名', value: 'topgrossingipadapplications' }
    // // iTunes Store：Mac App 排名
    // TOP_MAC: 'topmacapps',
    // // iTunes Store：免费 Mac App 排行
    // TOP_FREE_MAC: 'topfreemacapps',
    // // iTunes Store：畅销 Mac App 排名
    // TOP_GROSSING_MAC: 'topgrossingmacapps',
    // // iTunes Store：付费 Mac App 排行
    // TOP_PAID_MAC: 'toppaidmacapps',
    // // iTunes Store：新应用
    // NEW_IOS: 'newapplications',
    // // iTunes Store：新的免费应用
    // NEW_FREE_IOS: 'newfreeapplications',
    // // iTunes Store：新的付费应用
    // NEW_PAID_IOS: 'newpaidapplications',
}

// 苹果系统
export const AppleSystem = {
    ios: {
        name: 'ios',
        value: 'ios'
    },
    mac: {
        name: 'mac 暂无支持',
        value: 'mac'
    }
} as const

// 苹果设备
export const AppleDevice = {
    ipad: {
        name: 'ipad',
        value: 'ipad'
    },
    iphone: {
        name: 'iphone',
        value: 'iphone'
    }
} as const

// 苹果分类
export const AppleCategory = {
    // app 应用分类
    'app-children': { name: 'App 类别 · 儿童', id: 36, value: 36 },
    'app-business': { name: 'App 类别 · 商务', id: 6000, value: 6000 },
    'app-weather': { name: 'App 类别 · 天气', id: 6001, value: 6001 },
    'app-tools': { name: 'App 类别 · 工具', id: 6002, value: 6002 },
    'app-travel': { name: 'App 类别 · 旅游', id: 6003, value: 6003 },
    'app-sport': { name: 'App 类别 · 体育', id: 6004, value: 6004 },
    'app-socialize': { name: 'App 类别 · 社交', id: 6005, value: 6005 },
    'app-reference': { name: 'App 类别 · 参考资料', id: 6006, value: 6006 },
    'app-efficiency': { name: 'App 类别 · 效率', id: 6007, value: 6007 },
    'app-photography-video': { name: 'App 类别 · 摄影与录像', id: 6008, value: 6008 },
    'app-news': { name: 'App 类别 · 新闻', id: 6009, value: 6009 },
    'app-navigation': { name: 'App 类别 · 导航', id: 6010, value: 6010 },
    'app-music': { name: 'App 类别 · 音乐', id: 6011, value: 6011 },
    'app-life': { name: 'App 类别 · 生活', id: 6012, value: 6012 },
    'app-health-fitness': { name: 'App 类别 · 健康健美', id: 6013, value: 6013 },
    'app-game': { name: 'App 类别 · 游戏', id: 6014, value: 6014 },
    'app-finance': { name: 'App 类别 · 财务', id: 6015, value: 6015 },
    'app-entertainment': { name: 'App 类别 · 娱乐', id: 6016, value: 6016 },
    'app-edu': { name: 'App 类别 · 教育', id: 6017, value: 6017 },
    'app-books': { name: 'App 类别 · 图书', id: 6018, value: 6018 },
    'app-medical': { name: 'App 类别 · 医疗', id: 6020, value: 6020 },
    'app-newspapers': { name: 'App 类别 · 报刊杂志', id: 6021, value: 6021 },
    'app-food': { name: 'App 类别 · 美食佳饮', id: 6023, value: 6023 },
    'app-shop': { name: 'App 类别 · 购物', id: 6024, value: 6024 },
    'app-software_development': { name: 'App 类别 · 软件开发工具', id: 6026, value: 6026 },
    'app-graphics-design': { name: 'App 类别 · 图形与设计', id: 6027, value: 6027 },
    // 游戏应用分类
    'game-leisure': { name: '游戏类别 · 休闲', id: 7003, value: 7003 },
    'game-sport': { name: '游戏类别 · 体育', id: 7016, value: 7016 },
    'game-children': { name: '游戏类别 · 儿童', id: 36, value: 36 },
    'game-adventure': { name: '游戏类别 · 冒险', id: 7002, value: 7002 },
    'game-action': { name: '游戏类别 · 动作', id: 7001, value: 7001 },
    'game-card': { name: '游戏类别 · 卡牌', id: 7005, value: 7005 },
    'game-puzzle': { name: '游戏类别 · 字谜', id: 7019, value: 7019 },
    'game-family': { name: '游戏类别 · 家庭聚会', id: 7009, value: 7009 },
    'game-desktop': { name: '游戏类别 · 桌面', id: 7004, value: 7004 },
    'game-simulate': { name: '游戏类别 · 模拟', id: 7015, value: 7015 },
    'game-puzzle-riddle': { name: '游戏类别 · 益智解谜', id: 7012, value: 7012 },
    'game-speed': { name: '游戏类别 · 竞速', id: 7013, value: 7013 },
    'game-strategy': { name: '游戏类别 · 策略', id: 7017, value: 7017 },
    'game-cos': { name: '游戏类别 · 角色扮演', id: 7014, value: 7014 },
    'game-question': { name: '游戏类别 · 问答', id: 7018, value: 7018 },
    'game-music': { name: '游戏类别 · 音乐', id: 7011, value: 7011 }
} as const

export const AppleCountry = {
    dz: { value: 'dz', name: '阿尔及利亚', label: 'Algeria' },
    ao: { value: 'ao', name: '安哥拉', label: 'Angola' },
    ai: { value: 'ai', name: '安圭拉', label: 'Anguilla' },
    ag: { value: 'ag', name: '安提瓜和巴布达', label: 'Antigua and Barbuda' },
    ar: { value: 'ar', name: '阿根廷', label: 'Argentina' },
    am: { value: 'am', name: '亚美尼亚', label: 'Armenia' },
    au: { value: 'au', name: '澳大利亚', label: 'Australia' },
    at: { value: 'at', name: '奥地利', label: 'Austria' },
    az: { value: 'az', name: '阿塞拜疆', label: 'Azerbaijan' },
    bs: { value: 'bs', name: '巴哈马', label: 'Bahamas' },
    bh: { value: 'bh', name: '巴林', label: 'Bahrain' },
    bb: { value: 'bb', name: '巴巴多斯', label: 'Barbados' },
    by: { value: 'by', name: '白俄罗斯', label: 'Belarus' },
    be: { value: 'be', name: '比利时', label: 'Belgium' },
    bz: { value: 'bz', name: '伯利兹', label: 'Belize' },
    bj: { value: 'bj', name: '贝宁', label: 'Benin' },
    bm: { value: 'bm', name: '百慕大群岛', label: 'Bermuda' },
    bt: { value: 'bt', name: '不丹', label: 'Bhutan' },
    bo: { value: 'bo', name: '玻利维亚', label: 'Bolivia' },
    ba: { value: 'ba', name: '波斯尼亚和黑塞哥维那', label: 'Bosnia and Herzegovina' },
    bw: { value: 'bw', name: '博茨瓦纳', label: 'Botswana' },
    br: { value: 'br', name: '巴西', label: 'Brazil' },
    vg: { value: 'vg', name: '英属维尔京群岛', label: 'British Virgin Islands' },
    bg: { value: 'bg', name: '保加利亚', label: 'Bulgaria' },
    kh: { value: 'kh', name: '柬埔寨', label: 'Cambodia' },
    cm: { value: 'cm', name: '喀麦隆', label: 'Cameroon' },
    ca: { value: 'ca', name: '加拿大', label: 'Canada' },
    cv: { value: 'cv', name: '佛得角', label: 'Cape Verde' },
    ky: { value: 'ky', name: '开曼群岛', label: 'Cayman Islands' },
    td: { value: 'td', name: '乍得', label: 'Chad' },
    cl: { value: 'cl', name: '智利', label: 'Chile' },
    cn: { value: 'cn', name: '中国', label: 'China mainland' },
    co: { value: 'co', name: '哥伦比亚', label: 'Colombia' },
    cr: { value: 'cr', name: '哥斯达黎加', label: 'Costa Rica' },
    hr: { value: 'hr', name: '克罗地亚', label: 'Croatia' },
    cy: { value: 'cy', name: '塞浦路斯', label: 'Cyprus' },
    cz: { value: 'cz', name: '捷克共和国', label: 'Czech Republic' },
    ci: { value: 'ci', name: '科特迪瓦', label: "Côte d'Ivoire" },
    cd: { value: 'cd', name: '刚果民主共和国', label: 'Democratic Republic of the Congo' },
    dk: { value: 'dk', name: '丹麦', label: 'Denmark' },
    dm: { value: 'dm', name: '多米尼克', label: 'Dominica' },
    do: { value: 'do', name: '多米尼加共和国', label: 'Dominican Republic' },
    ec: { value: 'ec', name: '厄瓜多尔', label: 'Ecuador' },
    eg: { value: 'eg', name: '埃及', label: 'Egypt' },
    sv: { value: 'sv', name: '萨尔瓦多', label: 'El Salvador' },
    ee: { value: 'ee', name: '爱沙尼亚', label: 'Estonia' },
    sz: { value: 'sz', name: '爱沙尼亚', label: 'Eswatini' },
    fj: { value: 'fj', name: '斐济', label: 'Fiji' },
    fi: { value: 'fi', name: '芬兰', label: 'Finland' },
    fr: { value: 'fr', name: '法国', label: 'France' },
    ga: { value: 'ga', name: '加蓬', label: 'Gabon' },
    gm: { value: 'gm', name: '冈比亚', label: 'Gambia' },
    ge: { value: 'ge', name: '格鲁吉亚', label: 'Georgia' },
    de: { value: 'de', name: '德国', label: 'Germany' },
    gh: { value: 'gh', name: '加纳', label: 'Ghana' },
    gr: { value: 'gr', name: '希腊', label: 'Greece' },
    gd: { value: 'gd', name: '格林纳达', label: 'Grenada' },
    gt: { value: 'gt', name: '危地马拉', label: 'Guatemala' },
    gw: { value: 'gw', name: '几内亚比绍', label: 'Guinea-Bissau' },
    gy: { value: 'gy', name: '圭亚那', label: 'Guyana' },
    hn: { value: 'hn', name: '洪都拉斯', label: 'Honduras' },
    hk: { value: 'hk', name: '香港', label: 'Hong Kong' },
    hu: { value: 'hu', name: '匈牙利', label: 'Hungary' },
    is: { value: 'is', name: '冰岛', label: 'Iceland' },
    in: { value: 'in', name: '印度', label: 'India' },
    id: { value: 'id', name: '印度尼西亚', label: 'Indonesia' },
    iq: { value: 'iq', name: '伊拉克', label: 'Iraq' },
    ie: { value: 'ie', name: '爱尔兰', label: 'Ireland' },
    il: { value: 'il', name: '以色列', label: 'Israel' },
    it: { value: 'it', name: '意大利', label: 'Italy' },
    jm: { value: 'jm', name: '牙买加', label: 'Jamaica' },
    jp: { value: 'jp', name: '日本', label: 'Japan' },
    jo: { value: 'jo', name: '约旦', label: 'Jordan' },
    kz: { value: 'kz', name: '哈萨克斯坦', label: 'Kazakhstan' },
    ke: { value: 'ke', name: '肯尼亚', label: 'Kenya' },
    kr: { value: 'kr', name: '大韩民国', label: 'Korea, Republic of' },
    xk: { value: 'xk', name: '科索沃', label: 'Kosovo' },
    kw: { value: 'kw', name: '科威特', label: 'Kuwait' },
    kg: { value: 'kg', name: '吉尔吉斯斯坦', label: 'Kyrgyzstan' },
    la: { value: 'la', name: '老挝人民民主共和国', label: "Lao People's Democratic Republic" },
    lv: { value: 'lv', name: '拉脱维亚', label: 'Latvia' },
    lb: { value: 'lb', name: '黎巴嫩', label: 'Lebanon' },
    lr: { value: 'lr', name: '利比里亚', label: 'Liberia' },
    ly: { value: 'ly', name: '利比亚', label: 'Libya' },
    lt: { value: 'lt', name: '立陶宛', label: 'Lithuania' },
    lu: { value: 'lu', name: '卢森堡', label: 'Luxembourg' },
    mo: { value: 'mo', name: '澳门', label: 'Macao' },
    mg: { value: 'mg', name: '马达加斯加', label: 'Madagascar' },
    mw: { value: 'mw', name: '马拉维', label: 'Malawi' },
    my: { value: 'my', name: '马来西亚', label: 'Malaysia' },
    mv: { value: 'mv', name: '马尔代夫', label: 'Maldives' },
    ml: { value: 'ml', name: '马里', label: 'Mali' },
    mt: { value: 'mt', name: '马耳他', label: 'Malta' },
    mr: { value: 'mr', name: '毛里塔尼亚', label: 'Mauritania' },
    mu: { value: 'mu', name: '毛里求斯', label: 'Mauritius' },
    mx: { value: 'mx', name: '墨西哥', label: 'Mexico' },
    fm: { value: 'fm', name: '密克罗尼西亚联邦', label: 'Micronesia, Federated States of' },
    md: { value: 'md', name: '摩尔多瓦', label: 'Moldova' },
    mn: { value: 'mn', name: '蒙古', label: 'Mongolia' },
    me: { value: 'me', name: '黑山共和国', label: 'Montenegro' },
    ms: { value: 'ms', name: '蒙特塞拉特', label: 'Montserrat' },
    ma: { value: 'ma', name: '摩洛哥', label: 'Morocco' },
    mz: { value: 'mz', name: '莫桑比克', label: 'Mozambique' },
    mm: { value: 'mm', name: '缅甸', label: 'Myanmar' },
    na: { value: 'na', name: '纳米比亚', label: 'Namibia' },
    np: { value: 'np', name: '尼泊尔', label: 'Nepal' },
    nl: { value: 'nl', name: '荷兰', label: 'Netherlands' },
    nz: { value: 'nz', name: '新西兰', label: 'New Zealand' },
    ni: { value: 'ni', name: '尼加拉瓜', label: 'Nicaragua' },
    ne: { value: 'ne', name: '尼日尔', label: 'Niger' },
    ng: { value: 'ng', name: '尼日利亚', label: 'Nigeria' },
    mk: { value: 'mk', name: '北马其顿', label: 'North Macedonia' },
    no: { value: 'no', name: '挪威', label: 'Norway' },
    om: { value: 'om', name: '阿曼', label: 'Oman' },
    pa: { value: 'pa', name: '巴拿马', label: 'Panama' },
    pg: { value: 'pg', name: '巴布亚新几内亚', label: 'Papua New Guinea' },
    py: { value: 'py', name: '巴拉圭', label: 'Paraguay' },
    pe: { value: 'pe', name: '秘鲁', label: 'Peru' },
    ph: { value: 'ph', name: '菲律宾', label: 'Philippines' },
    pl: { value: 'pl', name: '波兰', label: 'Poland' },
    pt: { value: 'pt', name: '葡萄牙', label: 'Portugal' },
    qa: { value: 'qa', name: '卡塔尔', label: 'Qatar' },
    cg: { value: 'cg', name: '刚果共和国', label: 'Republic of the Congo' },
    ro: { value: 'ro', name: '罗马尼亚', label: 'Romania' },
    ru: { value: 'ru', name: '俄罗斯', label: 'Russia' },
    rw: { value: 'rw', name: '卢旺达', label: 'Rwanda' },
    sa: { value: 'sa', name: '沙特阿拉伯', label: 'Saudi Arabia' },
    sn: { value: 'sn', name: '塞内加尔', label: 'Senegal' },
    rs: { value: 'rs', name: '塞尔维亚', label: 'Serbia' },
    sc: { value: 'sc', name: '塞舌尔', label: 'Seychelles' },
    sl: { value: 'sl', name: '塞拉利昂', label: 'Sierra Leone' },
    sg: { value: 'sg', name: '新加坡', label: 'Singapore' },
    sk: { value: 'sk', name: '斯洛伐克', label: 'Slovakia' },
    si: { value: 'si', name: '斯洛文尼亚', label: 'Slovenia' },
    sb: { value: 'sb', name: '所罗门群岛', label: 'Solomon Islands' },
    za: { value: 'za', name: '南非', label: 'South Africa' },
    es: { value: 'es', name: '西班牙', label: 'Spain' },
    lk: { value: 'lk', name: '斯里兰卡', label: 'Sri Lanka' },
    kn: { value: 'kn', name: '圣基茨和尼维斯', label: 'St. Kitts and Nevis' },
    lc: { value: 'lc', name: '圣卢西亚', label: 'St. Lucia' },
    vc: { value: 'vc', name: '圣文森特和格林纳丁斯', label: 'St. Vincent and The Grenadines' },
    sr: { value: 'sr', name: '苏里南', label: 'Suriname' },
    se: { value: 'se', name: '瑞典', label: 'Sweden' },
    ch: { value: 'ch', name: '瑞士', label: 'Switzerland' },
    tw: { value: 'tw', name: '台湾', label: 'Taiwan' },
    tj: { value: 'tj', name: '塔吉克斯坦', label: 'Tajikistan' },
    tz: { value: 'tz', name: '坦桑尼亚', label: 'Tanzania' },
    th: { value: 'th', name: '泰国', label: 'Thailand' },
    to: { value: 'to', name: '汤加', label: 'Tonga' },
    tt: { value: 'tt', name: '特立尼达和多巴哥', label: 'Trinidad and Tobago' },
    tn: { value: 'tn', name: '突尼斯', label: 'Tunisia' },
    tm: { value: 'tm', name: '土库曼斯坦', label: 'Turkmenistan' },
    tc: { value: 'tc', name: '特克斯和凯科斯群岛', label: 'Turks and Caicos' },
    tr: { value: 'tr', name: '土耳其', label: 'Türkiye' },
    ae: { value: 'ae', name: '阿联酋', label: 'UAE' },
    ug: { value: 'ug', name: '乌干达', label: 'Uganda' },
    ua: { value: 'ua', name: '乌克兰', label: 'Ukraine' },
    gb: { value: 'gb', name: '英国', label: 'United Kingdom' },
    us: { value: 'us', name: '美国', label: 'United States' },
    uy: { value: 'uy', name: '乌拉圭', label: 'Uruguay' },
    uz: { value: 'uz', name: '乌兹别克斯坦', label: 'Uzbekistan' },
    vu: { value: 'vu', name: '瓦努阿图', label: 'Vanuatu' },
    ve: { value: 've', name: '委内瑞拉', label: 'Venezuela' },
    vn: { value: 'vn', name: '越南', label: 'Vietnam' },
    ye: { value: 'ye', name: '也门', label: 'Yemen' },
    zm: { value: 'zm', name: '赞比亚', label: 'Zambia' },
    zw: { value: 'zw', name: '津巴布韦', label: 'Zimbabwe' }
} as const
